#!/bin/bash

# address: ckt1qyqvkvvs6ljvm35stq796ksrev5ptnq9xwmst8xw53
# "args": "0xcb3190d7e4cdc690583c5d5a03cb2815cc0533b7"
# mine "args": "0x43d509d97f26007a285f39241cffcd411157196c"

get_cells_capacity() {
    local lock_args=$1

    printf '{
        "id": 2,
        "jsonrpc": "2.0",
        "method": "get_cells_capacity",
        "params": [
            {
                "script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": "%s"
                },
                "script_type": "lock"
            }
        ]
    }' $lock_args \
    | tr -d '\n' \
    | curl -S -s -H 'content-type: application/json' -d @- \
    http://localhost:8116
}

extract_capacity() {
    local resp=$1

    local strip_left=${resp#*capacity\":\"}
    local balance=${strip_left%\"\},\"id*}

    echo $balance
}

resp=$(get_cells_capacity $1)
extract_capacity $resp
