name: Contract Tests

on:
  push:
    branches:
    - 'v1*'
    - 'develop'
    - '*alphanet*'
    - '*testnet*'
  schedule:
  - cron:  '50 */12 * * *' # every 12 hour

jobs:
  contract-tests:
    if: github.repository == 'godwokenrises/godwoken-tests'
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        network: [gw_testnet_v1, gw_alphanet_v1]
    outputs:
      available: ${{ steps.check.outputs.available }}
    steps:
      - id: check
        env:
          KEY1: '${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }}'
          KEY2: '${{ secrets.GODWOKEN_TEST_PRIVATE_KEY2 }}'
          KEY3: '${{ secrets.GW_TESTNET_V1_TEST_PK }}'
        if: ${{ env.KEY1 != '' && env.KEY2 != '' && env.KEY3 != '' }}
        run: echo "available=true" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Node Cache
        uses: actions/cache@v3
        id: npm-and-yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('/home/runner/work/**/package-lock.json', '/home/runner/work/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
        
      - name: Install dependencies
        working-directory: contracts
        run: npm install
      - name: Run internal contract tests
        working-directory: contracts
        run: npm run test:${{ matrix.network }}
          # env:
          #   PRIVATE_KEY: ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY }}
          #   PRIVATE_KEY2: ${{ secrets.GODWOKEN_TEST_PRIVATE_KEY2 }}
          #   PRIVATE_KEY3: ${{ secrets.GW_TESTNET_V1_TEST_PK }}

          # - name: Run fee test 1 for 30 minutes
          #   working-directory: testcases/gw-fee-test
          #   run: |
          #     if [[ ${{ matrix.network == 'gw_alphanet_v1' }} ]]; then
          #       echo "NETWORK=alphanet" >> $GITHUB_ENV
          #     else
          #       echo "NETWORK=testnet" >> $GITHUB_ENV
          #     yarn && yarn account
          #     MODE=forever TIMEOUT_MS=1800000 TEST_CASE=1 POLL_TX_RECEIPT_TIME_OUT=45000 yarn start:$NETWORK
      - name: Run gasless tests
        working-directory: testcases/account-abstraction
        run: |
          yarn
          yarn run ci
          yarn run hardhat test --network ${{ matrix.network }}
