name: Fee-Test 

on:
  workflow_dispatch:

jobs:
  fee-test:
    strategy:
      fail-fast: false
      matrix:
        net: ['alphanet', 'testnet']
    runs-on: ubuntu-latest
    if: github.repository == 'godwokenrises/godwoken-tests'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Node Cache
      uses: actions/cache@v4
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Run Test 1 for 30 minutes
      working-directory: testcases/gw-fee-test
      run: |
        yarn && yarn account
        MODE=forever TIMEOUT_MS=1800000 TEST_CASE=1 POLL_TX_RECEIPT_TIME_OUT=45000 yarn start:${{ matrix.net }}
