name: Gasless-Test 

on:
  push:
  schedule:
  # You can schedule a workflow to run at specific UTC times using POSIX cron syntax (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07).
  # Scheduled workflows run on the latest commit on the default or base branch.
  # The shortest interval you can run scheduled workflows is once every 5 minutes.
  # Note: GitHub Actions does not support the non-standard syntax @yearly, @monthly, @weekly, @daily, @hourly, and @reboot.
  # You can use crontab guru (https://crontab.guru/) to help generate your cron syntax and confirm what time it will run.
  # To help you get started, there is also a list of crontab guru examples (https://crontab.guru/examples.html).
  - cron:  '20 */12 * * *' # every 12 hour

jobs:
  gasless-test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    if: github.repository == 'godwokenrises/godwoken-tests'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - name: Node Cache
      uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Run gasless tests
      working-directory: testcases/account-abstraction
      run: |
        yarn
        yarn run ci
        yarn run hardhat test --network gw_alphanet_v1
        yarn run hardhat test --network gw_testnet_v1
