name: Run Integration Test v1

on:
  push:
    branches:
    - 'v1'
    - 'develop'
  pull_request:

jobs:
  integration-test:
    uses: ./.github/workflows/reusable-integration-test-v1.yml
    with:
      # github.ref: The branch or tag ref that triggered the workflow run. For branches this is the format refs/heads/<branch_name>, and for tags it is refs/tags/<tag_name>.
      gw_prebuild_image_name: ghcr.io/zeroqn/godwoken-prebuilds
      gw_prebuild_image_tag: v1.1-feat-change-ckb-decimal-to-18
      tests_ref: ${{ github.event.pull_request.head.sha }}
